<?php

declare(strict_types=1);

namespace MarcoRieser\Livewire\Islands;

use Illuminate\Contracts\View\View;
use Illuminate\Support\Arr;
use Livewire\Component;
use Livewire\Features\SupportIslands\Compiler\IslandCompiler;
use MarcoRieser\Livewire\Hooks\SlotsAutoloader;
use MarcoRieser\Livewire\Tags\Livewire;
use RuntimeException;
use Statamic\Facades\Antlers;

class IslandManager
{
    /**
     * Build a stable token for an island: Livewire round-trips it through the
     * component memo and uses it to locate the island's cached view.
     */
    public function token(string $component, string $island): string
    {
        // Not a security context: the hash only produces a stable cache token.
        return 'antlers-'.hash('xxh3', $component.':'.$island);
    }

    /**
     * Cache the island's Antlers source next to Livewire's compiled islands,
     * with a Blade shim at the path Livewire expects, so island updates
     * render through the Antlers engine.
     */
    public function store(string $token, string $source): void
    {
        $sourcePath = $this->sourcePath($token);

        if (! is_dir(dirname($sourcePath))) {
            mkdir(dirname($sourcePath), 0755, true);
        }

        if (! file_exists($sourcePath) || file_get_contents($sourcePath) !== $source) {
            file_put_contents($sourcePath, $source);
        }

        $shimPath = IslandCompiler::getCachedPathFromToken($token);

        if (! file_exists($shimPath)) {
            // The token is generated by token() and only contains [a-z0-9-].
            file_put_contents($shimPath, sprintf(
                "<?php echo resolve(%s::class)->render('%s', get_defined_vars()); ?>",
                self::class,
                $token,
            ));
        }
    }

    /**
     * Render the island's Antlers source with the scope Livewire passes to
     * island views (the component's public properties and __livewire). On
     * placeholder passes (lazy, defer and skipped islands), only the
     * {{ livewire:placeholder }} pair content renders; without one the
     * placeholder is empty, mirroring Blade islands.
     *
     * @param  array<string, mixed>  $scope
     */
    public function render(string $token, array $scope): string
    {
        $sourcePath = $this->sourcePath($token);

        if (! file_exists($sourcePath) || ($source = file_get_contents($sourcePath)) === false) {
            throw new RuntimeException("The source of the island [{$token}] could not be found.");
        }

        $isPlaceholder = array_key_exists('__placeholder', $scope);

        // Runtime island data from renderIsland()/streamIsland() overrides
        // the scope captured by the island tag.
        $runtimeWith = $scope['__runtimeWith'] ?? [];
        $runtimeWith = is_array($runtimeWith) ? $runtimeWith : [];

        $scope = Arr::except($scope, ['__env', 'app', '__data', '__path', 'obLevel', '__placeholder', '__runtimeWith']);

        // Replace Livewire's Blade-only slot proxy with the antlers-friendly
        // slot html — islands render through the shim, so the SlotsAutoloader
        // render listener never runs for them.
        $component = $scope['__livewire'] ?? null;

        if ($component instanceof Component && ($slots = SlotsAutoloader::forComponent($component)) !== []) {
            $scope['slots'] = $slots;
        }

        $scope = [...$scope, ...$this->islandScope($token, $component), ...$runtimeWith];

        [$content, $placeholder] = $this->splitPlaceholder($source);

        if ($isPlaceholder) {
            return $placeholder === null ? '' : (string) Antlers::parse($placeholder, $scope, true);
        }

        return (string) Antlers::parse($content, $scope, true);
    }

    /**
     * Restore the island cache files of a component when they are missing —
     * after cleared view caches, or when the update request lands on a server
     * that never rendered the page. Re-rendering the component's view runs
     * the island tags, which write the files as a side effect.
     */
    public function ensureIslandFiles(Component $component): void
    {
        $missing = collect($component->getIslands())
            ->pluck('token')
            ->filter(fn (mixed $token): bool => is_string($token)
                && str_starts_with($token, 'antlers-')
                && (! file_exists($this->sourcePath($token)) || ! file_exists(IslandCompiler::getCachedPathFromToken($token))));

        if ($missing->isEmpty() || ! method_exists($component, 'render')) {
            return;
        }

        $view = $component->render();

        if ($view instanceof View) {
            $view->with(['__livewire' => $component])->render();
        }
    }

    /**
     * Split the island source into its content and the loading state defined
     * by a {{ livewire:placeholder }} tag pair. Placeholders of nested
     * islands stay with their island; without an own placeholder pair, the
     * placeholder is empty — mirroring Blade islands.
     *
     * @return array{string, string|null}
     */
    protected function splitPlaceholder(string $source): array
    {
        $tags = '(?:'.implode('|', Livewire::handles()).')';

        preg_match_all('/{{\s*(\/?)'.$tags.':island[^}]*}}/', $source, $islandTags, PREG_OFFSET_CAPTURE);
        preg_match_all('/{{\s*'.$tags.':placeholder\s*}}(.*?){{\s*\/'.$tags.':placeholder\s*}}/s', $source, $pairs, PREG_OFFSET_CAPTURE);

        $placeholder = null;
        $removals = [];

        foreach ($pairs[0] as $index => [$pair, $offset]) {
            // Only placeholder pairs outside of nested island pairs belong to
            // this island.
            $depth = 0;

            foreach ($islandTags[0] as $tagIndex => [$tag, $tagOffset]) {
                if ($tagOffset >= $offset) {
                    break;
                }

                $depth += $islandTags[1][$tagIndex][0] === '/' ? -1 : 1;
            }

            if ($depth !== 0) {
                continue;
            }

            $placeholder ??= trim($pairs[1][$index][0]);
            $removals[] = [$offset, strlen($pair)];
        }

        foreach (array_reverse($removals) as [$offset, $length]) {
            $source = substr_replace($source, '', $offset, $length);
        }

        return [$source, $placeholder];
    }

    /**
     * The island's persisted scope values, captured by the island tag.
     *
     * @return array<mixed>
     */
    protected function islandScope(string $token, mixed $component): array
    {
        if (! $component instanceof Component) {
            return [];
        }

        foreach ($component->getIslands() as $island) {
            if (($island['token'] ?? null) === $token) {
                $with = $island['with'] ?? [];

                return is_array($with) ? $with : [];
            }
        }

        return [];
    }

    protected function sourcePath(string $token): string
    {
        return dirname(IslandCompiler::getCachedPathFromToken($token))."/{$token}.antlers.html";
    }
}
