<?php

declare(strict_types=1);

namespace MarcoRieser\Livewire\Islands;

use Illuminate\Support\Arr;
use Livewire\Component;
use Livewire\Features\SupportIslands\Compiler\IslandCompiler;
use RuntimeException;
use Statamic\Facades\Antlers;

class IslandManager
{
    /**
     * Build a stable token for an island: Livewire round-trips it through the
     * component memo and uses it to locate the island's cached view.
     */
    public function token(string $component, string $island): string
    {
        // Not a security context: the hash only produces a stable cache token.
        return 'antlers-'.hash('xxh3', $component.':'.$island);
    }

    /**
     * Cache the island's Antlers source next to Livewire's compiled islands,
     * with a Blade shim at the path Livewire expects, so island updates
     * render through the Antlers engine.
     */
    public function store(string $token, string $source): void
    {
        $sourcePath = $this->sourcePath($token);

        if (! is_dir(dirname($sourcePath))) {
            mkdir(dirname($sourcePath), 0755, true);
        }

        if (! file_exists($sourcePath) || file_get_contents($sourcePath) !== $source) {
            file_put_contents($sourcePath, $source);
        }

        $shimPath = IslandCompiler::getCachedPathFromToken($token);

        if (! file_exists($shimPath)) {
            // The token is generated by token() and only contains [a-z0-9-].
            file_put_contents($shimPath, sprintf(
                "<?php echo resolve(%s::class)->render('%s', get_defined_vars()); ?>",
                self::class,
                $token,
            ));
        }
    }

    /**
     * Render the island's Antlers source with the scope Livewire passes to
     * island views (the component's public properties and __livewire). On
     * placeholder passes (lazy, defer and skipped islands), templates can
     * branch on {{ __is_placeholder }}; without such a branch the
     * placeholder is empty, mirroring Blade islands.
     *
     * @param  array<string, mixed>  $scope
     */
    public function render(string $token, array $scope): string
    {
        $sourcePath = $this->sourcePath($token);

        if (! file_exists($sourcePath) || ($source = file_get_contents($sourcePath)) === false) {
            throw new RuntimeException("The source of the island [{$token}] could not be found.");
        }

        $isPlaceholder = array_key_exists('__placeholder', $scope);

        if ($isPlaceholder && ! str_contains($source, '__is_placeholder')) {
            return '';
        }

        $scope = Arr::except($scope, ['__env', 'app', '__data', '__path', 'obLevel', '__placeholder']);

        $scope = [...$scope, ...$this->islandScope($token, $scope['__livewire'] ?? null)];

        $scope['__is_placeholder'] = $isPlaceholder;

        return (string) Antlers::parse($source, $scope, true);
    }

    /**
     * The island's persisted scope values, captured by the island tag.
     *
     * @return array<mixed>
     */
    protected function islandScope(string $token, mixed $component): array
    {
        if (! $component instanceof Component) {
            return [];
        }

        foreach ($component->getIslands() as $island) {
            if (($island['token'] ?? null) === $token) {
                $with = $island['with'] ?? [];

                return is_array($with) ? $with : [];
            }
        }

        return [];
    }

    protected function sourcePath(string $token): string
    {
        return dirname(IslandCompiler::getCachedPathFromToken($token))."/{$token}.antlers.html";
    }
}
