name: Test Suite

on:
  push:
  pull_request:

jobs:
  php_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            laravel: 10.*
            os: ubuntu-latest
            framework: "^10.0"
            testbench: "^8.0"
          - php: 8.3
            laravel: 11.*
            os: ubuntu-latest
            framework: "^11.0"
            testbench: "^9.0"
          - php: 8.4
            laravel: 12.*
            os: ubuntu-latest
            framework: "^12.0"
            testbench: "^10.0"

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.framework }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: vendor/bin/phpunit
