name: Test Suite

on:
  push:
  pull_request:

jobs:
  php_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: [12.*, 13.*]
        statamic: [5.*, 6.*]
        livewire: [4.*]
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - statamic: 5.*
            laravel: 13.*
          - laravel: 13.*
            php: 8.2

    name: PHP ${{ matrix.php }} - Statamic ${{ matrix.statamic }} - Laravel ${{ matrix.laravel }} - Livewire ${{ matrix.livewire }} - ${{ matrix.stability }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "statamic/cms:${{ matrix.statamic }}" "livewire/livewire:${{ matrix.livewire }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: vendor/bin/phpunit
